export const projects = [
  {
    title: 'Calendar',
    description: "During my internship at Docstream Solutions, I focused on developing a JavaScript plugin aimed at improving the user interface (UI) and user experience (UX) of a calendar system. Over the course of four months, I dedicated my efforts to this project, which involved displaying organized information from the backend in a user-friendly manner. The plugin also included essential CRUD (Create, Read, Update, Delete) functionalities to ensure seamless interaction and management of calendar data. This experience provided me with valuable insights into JavaScript development and UI/UX design principles within web applications.",
      image: '/images/calendarProject.png',
      tags: ['Javascript', 'HTML5', 'CSS3','JQuery'],
    source: '/',
    visit: '/',
    filesLink:[['/images/docstreamCertificate.png']],
    videoSrc:"https://www.youtube.com/watch?v=HCsihl7BsdQ&t=1s&ab_channel=JazaBacem",
    category: 'Professional',
    id: 0,
  },
  {
    title: 'PDF Viewer',
    description:"During my internship at Docstream Solutions, I undertook the development of another JavaScript plugin designed to enhance document management capabilities. This plugin, known as the PDF Viewer, allowed users to perform various actions on their PDF files directly within their web browser. Over the span of several months, I worked on implementing features such as zooming, cropping, and digital signing, aiming to provide users with a versatile tool for editing and managing their PDF documents seamlessly. This project provided me with invaluable experience in plugin development and integration, as well as a deeper understanding of user-centric design principles in web applications.",
    image: '/images/pdfProject.png',
    tags: ['Javascript', 'PDFJS', 'PDFLib','JQuery'],
    source: '/',
    visit: '/',
    filesLink:[['/images/docstreamCertificate.png']],
    videoSrc:"https://www.youtube.com/watch?v=b5AIhBprsHo&ab_channel=JazaBacem",
    category: 'Professional',
    id: 1,
  },
  {
    title: 'Re-design Site',
    description: "Working with such a fantastic company was truly a rewarding experience. Over the course of two months, I successfully updated their website utilizing a combination of WordPress, HTML, CSS, and a bit of PHP. Additionally, I navigated various plugins like Elementor, NinjaForms, ModernEventCalendar, and Jetpack. These tools greatly facilitated tasks related to design, form creation, security, and event management, making the overall process smoother and more efficient.",
      image: '/images/emcProject.png',
      tags: ['Wordpress', 'CSS3','HTML5','PHP'],
    source: '/',
    filesLink:[['images/manuel.png','files/manuel.pdf']],
    visit: 'https://www.emerillonmc.com',
    category: 'Professional',
    id: 2,
  },
  {
    title: 'Influence Connect',
    description: "",
    // image: '/images/testConnect.png',
    tags: ['NextJs', 'MongoDB', 'Prisma'],
    source: '/',
    visit: '/',
    filesLink:[['/images/adscoCertificate.png']],
    category: 'Professional',
    id: 3,
  },
  {
    title: 'My Portfolio',
    description: "You're already in it! Enjoying it so far?",
    image: '/images/portfolioProject.png',
    tags: ['NextJS','Styled Components'],
    source: '/',
    visit: '/',
    category: 'Local',
    id: 4,
  },
  {
    title: 'MyNotes',
    description: "This project marked my initial foray into creating a notes application, driven by my desire to explore and master ReactJs. The app was designed with CRUD functionalities specifically tailored for managing notes, allowing users to showcase and edit them as needed.",
    image: '/images/notesProject.png',
    tags: ['ReactJs','JSON server'],
    source: 'https://github.com/BacemJaza/My-Notes',
    videoSrc:"https://www.youtube.com/watch?v=3ZCaScGlryM&ab_channel=JazaBacem",
    visit: '/',
    category: 'Local',
    id: 5,
  },
  {
    title: 'Traffic run game',
    description: "A little dive into ThreeJS world and exploring game development with this simple application. This entertaining game challenges players to avoid colliding with other cars in order to progress.",
      image: '/images/runGame.png',
      tags: ['ThreeJS','JavaSript','HTML5','CSS3'],
    source: 'https://github.com/BacemJaza/traffic-run-game',
    visit: 'https://traffic-run-game-365j3rqr2-bacemjazas-projects.vercel.app',
    category: 'Local',
    id: 6,
  },
  {
    title: 'My Space',
    description: "",
    image: '',
    tags: [],
    source: '/',
    visit: '/',
    category: 'Local',
    id: 7,
  },
  {
    title: 'Instagram clone',
    description: "",
    image: '',
    tags: [],
    source: '/',
    visit: '/',
    category: 'Local',
    id: 8,
  },
  {
    title: 'Maven project',
    description: "This maven project was created for a school assignment. The accompanying file provides detailed insights into the algorithm's process and the aspects it tests, so I encourage you to review it.",
    image: '/images/mavenProject.png',
    tags: ['Maven','JUNIT','Java'],
    source: '/',
    visit: '/',
    filesLink:[['/images/mavenFile.png','files/mavenProject.pdf']],
    category: 'School',
    id: 9,
  },
  {
    title: 'E-commerce platform',
    description: "This Flutter-based mobile application was developed as part of a school project. It enables users to navigate through various products and make purchases. Working on this project introduced me to the capabilities of this exceptional framework and helped me appreciate its simplicity and structured approach.",
      image: '/images/ecommerceProject.png',
      tags: ["Flutter","Widgets","Tailwind"],
    source: '/',
    visit: '/',
    category: 'School',
    id: 10,
  }
];

export const TimeLineData = [
  {time: 2023, headline: 'Engineer to be.', school: "ESPRIT",schoolLink:"https://esprit.tn", description:"As we conclude our extensive academic journey at ESPRIT School, we reflect upon the profound experiences gained throughout this formidable educational odyssey. Within this comprehensive program, our focus on computer science has been unwavering, honing our expertise by integrating pre-existing knowledge with collaborative team projects. The invaluable guidance provided by our exceptionally skilled supervisors has been instrumental in shaping our academic trajectory.", position:"Student"},
  {time: 2019, headline: 'Licence to remember.', school: "ISIMM",schoolLink:"http://www.isimm.rnu.tn/public/", description:"Upon graduating from high school, my discerning choice led me to ISIMM—an institution that has proven to be an indelible cornerstone in my educational journey. From the onset, my decision to enroll at ISIMM has been a source of unwavering satisfaction, as it opened the doors to an expansive realm of computer science. Within the hallowed halls of ISIMM, I delved into a comprehensive curriculum that not only acquainted me with the intricacies of hardware and software utilities but also provided a platform for immersive learning. The educational landscape here has been transformative, facilitating a deep dive into the dynamic world of computer science, where theoretical knowledge seamlessly integrates with hands-on practical experience.", position:"Student"},
  { time: 2016, headline: 'Start of a bright career.', school: "Ksibet Mediouni High School",schoolLink:"https://www.facebook.com/p/Lycée-secondaire-Ksibet-El-Mediouni-100071554270419/?paipv=0&eav=AfbhkMUBHjf_uNaIDtD4GxWjuZ8d2zMbGHyVboQjbJjlSBuJ4_UWWyqEuqb7hGSmuf4&_rdr", description:"Studying at Ksibet Mediouni High School represents an exceptional academic journey, particularly for those inclined towards mathematical and scientific logics. The institution, known for its commitment to excellence in education, provides a structured and professional environment that nurtures intellectual curiosity and fosters a deep understanding of mathematical and scientific principles.", position:"Student"},
];
export const TechnologiesData = [
  {title:"Programming Languages", description:[{name:"Python",icon:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/115px-Python-logo-notext.svg.png"},{name:"C", icon:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/C_Programming_Language.svg/280px-C_Programming_Language.svg.png"},{name:"C++", icon:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/131px-ISO_C%2B%2B_Logo.svg.png"},{name:"JAVA", icon:"https://upload.wikimedia.org/wikipedia/fr/thumb/2/2e/Java_Logo.svg/180px-Java_Logo.svg.png"}]},
  { title:"FrontEnd", description:[{name:"NextJs",icon:"https://static-00.iconduck.com/assets.00/nextjs-icon-512x512-y563b8iq.png"},{name:"ReactJs", icon:"https://cdn.worldvectorlogo.com/logos/react-2.svg"},{name:"AngularJS", icon:"https://angular.io/assets/images/logos/angularjs/AngularJS-Shield.svg"}]},
  {title:"BackEnd", description:[{name:"DJANGO",icon:"https://seeklogo.com/images/D/django-logo-4C5ECF7036-seeklogo.com.png"},{name:"Spring BOOT", icon:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Spring_Boot.svg/120px-Spring_Boot.svg.png"}]},
  {title:"Mobile", description:[{name:"Android Studio",icon:"https://1.bp.blogspot.com/-LgTa-xDiknI/X4EflN56boI/AAAAAAAAPuk/24YyKnqiGkwRS9-_9suPKkfsAwO4wHYEgCLcBGAsYHQ/s0/image9.png"},{name:"Flutter", icon:"https://www.ideematic.com/wp-content/uploads/2020/07/flutter_logo-300x300.png"}]},
  {title:"Team Managment", description:[{name:"Jira",icon:"http://jira.discovery.com.tn:9090/images/atlassian-jira-logo-large.png"},{name:"SCRUM", icon:"https://www.scrum.org/themes/custom/scrumorg_v2/assets/images/logo-250.png"}]},
]

export const mods = [
  {
    title: 'Web Developer',
    description: "Enthusiastic self made Developer with professional experiences",
      image: '/images/Developer.png',
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0
  },
  {
    title: 'Engineering student',
    description:"Esprit Software engeneering student",
    image: '/images/Study.png',
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1
  },
  // {
  //   title: '3D Designer',
  //   description: "",
  //     image: '/images/3.jpg',
  //     tags: [],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 2,
  // },
  // {
  //   title: 'Unichat',
  //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //   image: '/images/4.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 3,
  // },
];

export const accomplishmentsData = [
  { image:'/images/ieee.jpg', title: "IEEE",text: 'Participating in IEEE and joining TSYP 2021 was a dynamic experience filled with conferences, workshops, and ample networking opportunities. The diverse sessions allowed for in-depth learning and collaboration, while the social activities and entertainment provided moments of relaxation and amusement. The event successfully blended professional development with personal connections, making it a valuable and enjoyable experience.' },
  { image:'/images/hultPrize.jpg',title: "Hult Prize", text: 'In the Hult Prize 2020 competition, our team of four dedicated individuals passionately addressed the global challenge of food insecurity. Focusing on a sustainable and community-driven solution, we proposed the creation of an innovative application. The app aimed to connect students with local housewives who would prepare nutritious, well-balanced meals. The unique aspect of our concept was that these housewives would not only contribute to combating food insecurity but also earn a fair income for their culinary skills.Our team worked diligently to develop a comprehensive business plan and prototype for the application, emphasizing the social impact it could have on both students and the community. Through careful consideration of economic, cultural, and logistical factors, we crafted a solution that not only provided students with convenient access to wholesome meals but also empowered local women economically.Our efforts and commitment were recognized by the Hult Prize 2020 judges, resulting in our team securing the second runner-up position in the competition.', },
  { image:'/images/atast.jpg', title: "ATAST",text: "In the 2020 ATAST event, our team of five presented a groundbreaking solution: a smart garbage collector. Using IoT sensors and data analytics, our system optimized waste collection, reducing environmental impact. The innovation included features to identify and separate recyclables, promoting recycling and contributing to a circular economy. Our participation highlighted a commitment to leveraging technology for sustainable development." },
  { image:'/images/apek.jpg',title: "APEK", text: "Over the course of three years with APEK, the environmental hometown association dedicated to safeguarding the environment, I actively contributed to its mission, navigating challenges related to finances, networking, and logistics. In 2017, I assumed the role of program planner for a pivotal conference that focused on the environmental landscape in Tunisia by envisioning potential challenges in 2030 and proposing proactive solutions.In my capacity as program planner, I collaborated with experts, educators, and professionals to curate an impactful conference agenda. The event aimed to gather well-educated individuals from Tunisia to raise awareness about imminent environmental issues and foster discussions on preventive measures. Through meticulous planning, I ensured the seamless execution of the conference, addressing logistical intricacies and maximizing the impact of the discussions.Simultaneously, I actively engaged in addressing financial constraints by exploring sponsorship opportunities, securing funding, and optimizing resource allocation. Building a robust network within and outside the association became crucial, facilitating collaborations and partnerships that strengthened APEK's initiatives.Over the three years, my involvement in APEK evolved, encompassing a holistic approach to environmental protection. From grappling with financial challenges to establishing a robust network and navigating logistical complexities, my tenure was marked by a commitment to the association's overarching goal of creating a sustainable and resilient environmental future for Tunisia."},
];